### ISSUE TITLE
this project was dead？

### ISSUE THREAD

**Issue by evolutionjay** [adam-p/markdown-here-safari#6]
this project was dead？

**Comment by adam-p** [comment]
I haven't worked on it since Apple changed their extension store/gallery stuff and required extension devs to pay $100 for a dev account. I plan on getting it working again in the not-too-distant future, but for now... it's hibernating.

**Comment by evolutionjay** [comment]
This is a great open source project, please do not own a person to bear the full cost, please try to donate, you can make this project better
